import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MetaMediaService } from '../../core/services/meta-media.service';
import { ContentService } from '../../core/services/content/content.service';
import { AudioService } from '../../core/services/audio.service';
import { IContent } from '../../models/content/icontent';
import { MetaMedia } from '../../models/meta-media/meta-media';
import { Post } from '../../models/content/wordpress/post';
import { ItemVideo } from '../../models/content/youtube/item-video';

@Component({
  selector: 'app-content-details',
  templateUrl: './content-details.component.html',
  styleUrl: './content-details.component.scss'
})
export class ContentDetailsComponent implements OnInit {
  currentMetaMedia!: MetaMedia;
  content!: IContent;
  loading = true;
  safeHtmlContent?: SafeHtml;
  audioUrl?: string;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private metaMediaService: MetaMediaService,
    private contentService: ContentService<IContent>,
    private audioService: AudioService,
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit(): void {
    this.currentMetaMedia = this.metaMediaService.currentMetaMedia;

    const contentId = this.route.snapshot.paramMap.get('id');
    if (contentId) {
      this.loadContent(contentId);
    }
  }

  loadContent(id: string): void {
    this.loading = true;
    this.contentService.getContentById(id).subscribe({
      next: (content: IContent) => {
        this.content = content;

        // For WordPress posts, sanitize HTML content
        if (content instanceof Post && content.content) {
          this.safeHtmlContent = this.sanitizer.bypassSecurityTrustHtml(content.content.rendered);

          // Try to extract audio URL from HTML content (legacy method)
          this.extractAudioUrl(content.content.rendered);
        }

        // Try to get audio from backend API (generated by Azure TTS)
        this.loadAudioFromBackend(id);

        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading content:', error);
        this.loading = false;
        // Navigate back if content not found
        this.router.navigate(['/media', this.currentMetaMedia.key]);
      }
    });
  }

  loadAudioFromBackend(contentId: string): void {
    this.audioService.getAudioUrlByContentId(contentId).subscribe({
      next: (response) => {
        if (response && response.url) {
          this.audioUrl = response.url;
        }
      },
      error: (error) => {
        // L'audio n'est peut-être pas disponible pour ce contenu, ce n'est pas grave
        console.log('No audio available for this content:', error);
      }
    });
  }

  extractAudioUrl(htmlContent: string): void {
    // Try to extract audio URL from WordPress audio shortcode or HTML5 audio tag
    const audioRegex = /<audio[^>]*src=["']([^"']+)["']/i;
    const match = htmlContent.match(audioRegex);

    if (match && match[1]) {
      this.audioUrl = match[1];
    }
  }

  getTitle(): string {
    if (!this.content) return '';
    return this.content.title || 'Sans titre';
  }

  getDate(): Date | undefined {
    if (!this.content) return undefined;
    return this.content.publishedAt;
  }

  getImageUrl(): string | undefined {
    if (!this.content) return undefined;

    if (this.content instanceof Post && this.content.image) {
      return this.content.image.url;
    }
    if (this.content instanceof ItemVideo && this.content.image) {
      return this.content.image.url;
    }
    return undefined;
  }

  goBack(): void {
    this.router.navigate(['/media', this.currentMetaMedia.key]);
  }

  share(): void {
    if (navigator.share && this.content) {
      const post = this.content as Post;
      navigator.share({
        title: this.getTitle(),
        text: this.getTitle(),
        url: post.link || window.location.href
      }).catch((error) => console.log('Error sharing:', error));
    }
  }

  get canShare(): boolean {
    return !!navigator.share;
  }
}
